export const ERROR_ONLY_ONE_SPOT_NFT_ALLOWED: string = 'only one spot can nft be redeemed for promotion'
export const ERROR_INVALID_WORD_COUNT: string = 'invalid word count in memo'
export const ERROR_INVALID_PROMOTION_TYPE: string = 'invalid promotion type'
export const ERROR_COLLECTION_NOT_EXISTS: string = 'collection not exists'
export const ERROR_AUCTION_NOT_EXISTS: string = 'auction not exists'
export const ERROR_INVALID_PROMOTION_TYPE_AUCTION_GOLD_ONLY = 'invalid promotion type - auction only allowed for gold spot'
export const ERROR_INVALID_NFT_SILVER_SPOT_EXPECTED: string = 'invalid nft - silver spot expected'
export const ERROR_NOT_ALLOWED_AUCTION_NOT_STARTED: string = 'not allowed - auction not started yet'