name: Smart Contract Tests
on:
  push:

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: yarn run test